### ISSUE TITLE
HDRP

### ISSUE THREAD

**Issue by lejeanf** [Barbelot/FluidAutomata#1]
is it possible to transfer it for hdrp?

**Comment by Barbelot** [comment]
Yes, you just need to create a shader with ShaderGraph that has an exposed  texture property with reference "_FluidTexture".
Then if you create a material using this shader and link it in the FluidAutomataController it should work.

Basically all the computations are independant of the pipeline used and end up in the RenderTexture "fluidTexture" of the FluidAutomataController. You can then bind this texture to any material (or other script).

In this example the texture is binded to a material using `fluidMaterial.SetTexture("_FluidTexture", fluidTexture);` in the InitializeFluidTexture function of the FluidAutomataController. As long as the shader of the fluidMaterial as a texture property referenced by "_FluidTexture" it will work.
